FROM undefined/local/mariner-glibc:latest AS keysinuse_base

FROM mcr.microsoft.com/cbl-mariner/base/core:1.0

# Install dependencies for functional test and make
# LSAN failures informational only
ENV LSAN_OPTIONS=exitcode=0
RUN tdnf install -y build-essential

RUN mkdir /keysinuse
COPY --from=keysinuse_base /keysinuse /keysinuse
RUN /keysinuse/install.sh
RUN rm -rf /keysinuse

COPY --from=keysinuse_base /keysinuse_test/keysinuse_functional /usr/bin

ENTRYPOINT [ "/usr/bin/keysinuse_functional" ]