FROM alpine

# Fetch build dependencies
RUN apk add cmake openssl-dev build-base linux-headers go

# Copy project files
RUN mkdir /keysinuse-openssl /keysinuse /keysinuse_test
COPY ./cmake-toolchains/linux-amd64-musl.cmake  /keysinuse-openssl
COPY ./CMakeLists.txt                           /keysinuse-openssl/CMakeLists.txt
COPY ./engine                                   /keysinuse-openssl/engine
COPY ./test                                     /keysinuse-openssl/test
COPY ./packaging/util                           /keysinuse-openssl/packaging/util
COPY ./containers/install.sh                    /keysinuse
RUN chmod 0755 /keysinuse/install.sh

# Build C/CPP binaries
WORKDIR /keysinuse-openssl
RUN cmake -DCMAKE_TOOLCHAIN_FILE=./linux-amd64-musl.cmake -H./ -B./build
RUN cmake --build ./build --target keysinuse
RUN cmake --build ./build --target keysinuse_test_common
RUN cmake --build ./build --target keysinuse_functional

# Build install helper
WORKDIR /keysinuse-openssl/packaging/util
RUN make /keysinuse-openssl/bin/keysinuseutil

# Copy files to staging
RUN cp /keysinuse-openssl/bin/keysinuse.so               /keysinuse
RUN cp /keysinuse-openssl/bin/keysinuseutil              /keysinuse
RUN cp /keysinuse-openssl/bin/test/keysinuse_functional  /keysinuse_test

# Remove project files
RUN rm -rf /keysinuse-openssl