FROM undefined/local/alpine-musl:latest AS keysinuse_base

FROM alpine

# Install dependencies for functional test
RUN apk add openssl libgcc libstdc++

RUN mkdir /keysinuse
COPY --from=keysinuse_base /keysinuse /keysinuse
RUN /keysinuse/install.sh
RUN rm -rf /keysinuse

COPY --from=keysinuse_base /keysinuse_test/keysinuse_functional /usr/bin

ENTRYPOINT [ "/usr/bin/keysinuse_functional" ]