FROM undefined/local/mariner-glibc:latest AS keysinuse_base

FROM mcr.microsoft.com/cbl-mariner/base/core:1.0

ENV LSAN_OPTIONS=exitcode=0

RUN tdnf install -y build-essential

RUN mkdir /keysinuse
RUN mkdir /usr/lib/keysinuse
COPY --from=keysinuse_base /keysinuse /keysinuse
RUN mv /keysinuse/keysinuse.so /usr/lib/keysinuse.so
RUN /keysinuse/installkeysinuse configure

COPY --from=keysinuse_base /keysinuse-openssl/bin/test/keysinuse_functional /

ENTRYPOINT [ "/keysinuse_functional" ]