FROM alpine

# Fetch build dependencies
RUN apk add cmake openssl-dev build-base linux-headers go

# Copy project files
RUN mkdir /keysinuse-openssl
COPY ./CMakeLists.txt   /keysinuse-openssl/CMakeLists.txt
COPY ./cmake-toolchains /keysinuse-openssl/cmake-toolchains
COPY ./engine           /keysinuse-openssl/engine
COPY ./test             /keysinuse-openssl/test
COPY ./packaging        /keysinuse-openssl/packaging

# Build C/CPP binaries
WORKDIR /keysinuse-openssl
RUN cmake -DCMAKE_TOOLCHAIN_FILE=./cmake-toolchains/linux-amd64-musl.cmake -H./ -B./build
RUN cmake --build ./build --target keysinuse
RUN cmake --build ./build --target keysinuse_test_common
RUN cmake --build ./build --target keysinuse_functional

# Build install helper
WORKDIR /keysinuse-openssl/packaging
RUN make /keysinuse-openssl/bin/keysinuseutil

# Copy files to staging
RUN mkdir /usr/lib/keysinuse
RUN cp /keysinuse-openssl/bin/keysinuse.so            /usr/lib/keysinuse
RUN cp /keysinuse-openssl/bin/keysinuseutil           /usr/lib/keysinuse
RUN cp /keysinuse-openssl/packaging/common/postinst    /usr/lib/keysinuse/installkeysinuse
RUN chmod 0755 /usr/lib/keysinuse/installkeysinuse