FROM mcr.microsoft.com/cbl-mariner/base/core:1.0 as build

# Fetch build dependencies
RUN tdnf install -y build-essential openssl-devel cmake golang ca-certificates-microsoft

# Copy project files
COPY ./ /keysinuse-openssl

# Build C/CPP binaries
WORKDIR /keysinuse-openssl
RUN cmake -DCMAKE_TOOLCHAIN_FILE=./cmake-toolchains/linux-amd64-glibc.cmake -H./ -B./build
RUN cmake --build ./build --target keysinuse

# Build install helper
WORKDIR /keysinuse-openssl/packaging/util
RUN make /keysinuse-openssl/bin/keysinuseutil

FROM mcr.microsoft.com/cbl-mariner/distroless/minimal:2.0

# Copy files to staging
COPY --chmod=0755 ./containers/install.sh                       /keysinuse/install.sh
COPY --from=build /keysinuse-openssl/bin/keysinuse.so               /keysinuse/keysinuse.so
COPY --from=build /keysinuse-openssl/bin/keysinuseutil              /keysinuse/keysinuseutil