FROM undefined/local/mariner-glibc:latest AS keysinuse_base

FROM ubuntu:20.04

ENV LSAN_OPTIONS=exitcode=0

RUN apt-get update
RUN apt-get install -y openssl libasan5

RUN mkdir /keysinuse
RUN mkdir /usr/lib/keysinuse
COPY --from=keysinuse_base /keysinuse /keysinuse
RUN mv /keysinuse/keysinuse.so /usr/lib/keysinuse.so
RUN /keysinuse/installkeysinuse configure

COPY --from=keysinuse_base /keysinuse-openssl/bin/test/keysinuse_functional /

ENTRYPOINT [ "/keysinuse_functional" ]