ARG tag=20.04

FROM undefined/local/mariner-glibc:latest AS keysinuse_base

FROM ubuntu:$version

# Install dependencies for functional test and make
# LSAN failures informational only
ENV LSAN_OPTIONS=exitcode=0
RUN apt-get update
RUN apt-get install -y openssl libasan5

RUN mkdir /keysinuse
COPY --from=keysinuse_base /keysinuse /keysinuse
RUN /keysinuse/install.sh
RUN rm -rf /keysinuse

COPY --from=keysinuse_base /keysinuse_test/keysinuse_functional /usr/bin

ENTRYPOINT [ "/usr/bin/keysinuse_functional" ]