ARG tag=2.0

FROM undefined/local/keysinuse-glibc:latest AS keysinuse_base

FROM mcr.microsoft.com/cbl-mariner/base/core:$version

# Install dependencies for functional test and make
# LSAN failures informational only
ENV LSAN_OPTIONS=exitcode=0
RUN tdnf install -y build-essential

RUN mkdir /keysinuse
COPY --from=keysinuse_base /keysinuse /keysinuse
RUN /keysinuse/install.sh
RUN rm -rf /keysinuse

COPY --from=keysinuse_base /keysinuse_test/keysinuse_functional /usr/bin

ENTRYPOINT [ "/usr/bin/keysinuse_functional" ]