#!/bin/sh -e

case $1 in
  configure | 1 | 2)
  # Create a directory for keys in use logs
  if [ ! -e /var/log/keysinuse ]; then
    mkdir /var/log/keysinuse
  fi
  chown root:root /var/log/keysinuse
  chmod 1733 /var/log/keysinuse

  # Save a copy of the old config before we attempt to update it
  config=$(/usr/bin/openssl version -d | awk '{gsub(/"/, "", $2); print $2}')/openssl.cnf
  config=$(readlink -f $config)

  if [ -x $config ]; then
    cp $config $config.prekeysinuse
  else
    touch $config
  fi

  # Configure OpenSSL to use the engine
  if [ -x /usr/bin/keysinuseutil ]; then
    echo "Enabling keysinuse engine for OpenSSL"
    LD_PRELOAD="libpthread.so.0" /usr/bin/keysinuseutil -update-default -install-library install || echo "Configuring engine failed"
  fi
esac

exit 0
