#!/bin/sh -e

case $1 in
  configure | 1 | 2)
  # Create a directory for keys in use logs
  if [ ! -e /var/log/keysinuse ]; then
    mkdir /var/log/keysinuse
  fi
  chown root:root /var/log/keysinuse
  chmod 1733 /var/log/keysinuse

  # Link to engine from engines directory
  ln -s $(/usr/bin/openssl version -e | awk '{gsub(/"/, "", $2); print $2}')/keysinuse.so /usr/lib/keysinuse/keysinuse.so 

  # Save a copy of the old config before we attempt to update it
  config=$(/usr/bin/openssl version -d | awk '{gsub(/"/, "", $2); print $2}')/openssl.cnf
  config=$(readlink -f $config)

  if [ -x $config ]; then
    cp $config $config.prekeysinuse
  else
    touch $config
  fi

  # Configure OpenSSL to use the engine
  if [ -x /usr/bin/keysinuseutil ]; then
    echo "Enabling keysinuse engine for OpenSSL"
    /usr/bin/keysinuseutil -update-default install || echo "Configuring engine failed"
  fi

  # Config used to reside in /usr/lib/keysinuse. Create symlink for
  # backwards compat and discoverability
  if [ -x /etc/keysinuse/keysinuse.cnf ]; then
    ln -s /usr/lib/keysinuse/keysinuse.cnf /etc/keysinuse/keysinuse.cnf
  fi
esac

exit 0
