#!/bin/bash -e

case $1 in
  remove | upgrade | 0)
  # Deconfigure enginepo
  if [ -x /usr/bin/keysinuseutil ]; then
    echo "Disabling keysinuse engine for OpenSSL"
    /usr/bin/keysinuseutil -update-default uninstall || echo "Deconfiguring keysinuse engine failed"
  fi

  # Clean up symlink to engine in engines directory
  engine_link=$(/usr/bin/openssl version -e | awk '{gsub(/"/, "", $2); print $2}')/keysinuse.so
  if [ -e $engine_link ]; then
    rm $engine_link
  fi

  # Clean up symlink to config in library directory
  config_link=/usr/lib/keysinuse/keysinuse.cnf
  if [ -e $config_link ]; then
    rm $config_link
  fi
esac

exit 0