stages:
  - stage: container_build
    displayName: Container Build

    jobs:
    - job: glibc
      displayName: Glibc (Mariner)

      pool:
        type: docker
        os: linux

      variables:
        ob_git_checkout: true
        ob_outputDirectory: '$(Build.SourcesDirectory)/out'

      steps:
        - task: onebranch.pipeline.imagebuildinfo@1
          displayName: 'Build Glibc Base Image'
          inputs:
            repositoryName: local/mariner-glibc
            dockerFileRelPath: ./containers/Dockerfile-Mariner_Glibc
            dockerFileContextPath : ./
            saveImageToPath: mariner-glibc.tar
            enable_network: true
            enable_pull: false
            build_tag: latest
            enable_service_tree_acr_path: false

        - task: onebranch.pipeline.imagebuildinfo@1
          displayName: 'Build Mariner Test'
          inputs:
            repositoryName: local/mariner-test
            dockerFileRelPath: ./containers/Dockerfile-Mariner_Test
            dockerFileContextPath : ./
            saveImageToPath: mariner-test.tar
            enable_network: true
            enable_pull: false
            build_tag: latest
            enable_service_tree_acr_path: false

        - task: onebranch.pipeline.imagebuildinfo@1
          displayName: 'Build Ubuntu Test'
          inputs:
            repositoryName: local/ubuntu-2004-test
            dockerFileRelPath: ./containers/Dockerfile-Ubuntu_2004_Test
            dockerFileContextPath : ./
            saveImageToPath: ubuntu-2004-test.tar
            enable_network: true
            enable_pull: false
            build_tag: latest
            enable_service_tree_acr_path: false

    - job: musl
      displayName: Musl (Alpine)

      pool:
        type: docker
        os: linux

      variables:
        ob_git_checkout: true

      steps:
        - task: onebranch.pipeline.imagebuildinfo@1
          displayName: 'Build Musl Base Image'
          inputs:
            repositoryName: local/alpine-musl
            dockerFileRelPath: ./containers/Dockerfile-Alpine_Musl
            dockerFileContextPath : ./
            saveImageToPath: alpine-musl.tar
            enable_network: true
            enable_pull: false
            build_tag: latest
            enable_service_tree_acr_path: false

        - task: onebranch.pipeline.imagebuildinfo@1
          displayName: 'Build Alpine Test'
          inputs:
            repositoryName: local/alpine-test
            dockerFileRelPath: ./containers/Dockerfile-Alpine_Test
            dockerFileContextPath : ./
            saveImageToPath: alpine-test.tar
            enable_network: true
            enable_pull: false
            build_tag: latest
            enable_service_tree_acr_path: false